"""Generate deterministic synthetic demo inputs and real CLI evidence."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import textwrap
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont, ImageOps

from receipt_extractor import file_io, replay

CANVAS = "#0b1020"
PANEL = "#121a2e"
PANEL_LIGHT = "#19243d"
TEXT = "#edf2ff"
MUTED = "#9aa8c7"
CYAN = "#57d3ff"
GREEN = "#63e6a5"
AMBER = "#ffc857"
RED = "#ff7b8b"
PURPLE = "#a78bfa"
RECEIPT = "#fffdf7"
INK = "#172033"
RECEIPT_MUTED = "#657087"


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    """Use Pillow's pinned bundled font instead of a host font."""
    return ImageFont.load_default(size=size)


def _text_width(draw: ImageDraw.ImageDraw, text: str, *, size: int) -> int:
    box = draw.textbbox((0, 0), text, font=_font(size))
    return round(box[2] - box[0])


def _centered(
    draw: ImageDraw.ImageDraw,
    y: int,
    text: str,
    *,
    width: int,
    size: int,
    fill: str,
) -> None:
    x = (width - _text_width(draw, text, size=size)) // 2
    draw.text((x, y), text, font=_font(size), fill=fill)


def _receipt(
    *,
    vendor: str,
    subtitle: str,
    lines: Sequence[tuple[str, str]],
    subtotal: str,
    tax: str,
    total: str,
) -> Image.Image:
    width, height = 720, 1080
    image = Image.new("RGB", (width, height), RECEIPT)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle(
        (18, 18, width - 18, height - 18),
        radius=26,
        outline="#d5d9e2",
        width=3,
    )
    _centered(
        draw, 68, "SYNTHETIC - NOT A REAL RECEIPT", width=width, size=19, fill=RED
    )
    _centered(draw, 126, vendor.upper(), width=width, size=44, fill=INK)
    _centered(draw, 188, subtitle, width=width, size=22, fill=RECEIPT_MUTED)
    _centered(
        draw,
        238,
        "2026-07-24  12:40 UTC",
        width=width,
        size=19,
        fill=RECEIPT_MUTED,
    )
    draw.line((72, 300, width - 72, 300), fill="#cfd5df", width=3)

    y = 342
    for label, price in lines:
        draw.text((82, y), label, font=_font(25), fill=INK)
        price_width = _text_width(draw, price, size=25)
        draw.text((width - 82 - price_width, y), price, font=_font(25), fill=INK)
        y += 68

    draw.line((72, 650, width - 72, 650), fill="#cfd5df", width=3)
    totals = (("SUBTOTAL", subtotal), ("TAX", tax))
    y = 694
    for label, value in totals:
        draw.text((82, y), label, font=_font(23), fill=RECEIPT_MUTED)
        value_width = _text_width(draw, value, size=23)
        draw.text(
            (width - 82 - value_width, y),
            value,
            font=_font(23),
            fill=RECEIPT_MUTED,
        )
        y += 58

    draw.rounded_rectangle(
        (66, 822, width - 66, 916),
        radius=18,
        fill="#eaf0ff",
        outline="#b8c7ef",
        width=2,
    )
    draw.text((88, 848), "TOTAL", font=_font(30), fill=INK)
    total_width = _text_width(draw, total, size=34)
    draw.text(
        (width - 88 - total_width, 843),
        total,
        font=_font(34),
        fill=INK,
    )
    _centered(
        draw,
        970,
        "Fixture generated by scripts/capture_demo.py",
        width=width,
        size=18,
        fill=RECEIPT_MUTED,
    )
    return image


def _save_inputs(input_dir: Path) -> None:
    input_dir.mkdir(parents=True, exist_ok=True)
    cafe = _receipt(
        vendor="Cafe Lumen",
        subtitle="Fictional demo vendor",
        lines=(("Oat latte", "$6.40"), ("Lunch bowl", "$10.20")),
        subtotal="$16.60",
        tax="$1.80",
        total="$18.40",
    )
    metro = _receipt(
        vendor="Metro Line",
        subtitle="Fictional demo transit",
        lines=(("Single ride", "$3.00"),),
        subtotal="$3.00",
        tax="$0.25",
        total="$3.25",
    )
    cafe.save(input_dir / "cafe-lumen.png", format="PNG", compress_level=9)
    metro.save(
        input_dir / "metro-line.webp",
        format="WEBP",
        lossless=True,
        quality=100,
        method=6,
    )


def _manifest_document(images: Sequence[file_io.ImagePayload]) -> dict[str, Any]:
    outputs = {
        "cafe-lumen.png": {
            "date": "2026-07-24",
            "amount": "$18.40",
            "vendor": "Cafe Lumen",
            "category": "Meals",
        },
        "metro-line.webp": {
            "date": "2026-07-24",
            "amount": "$3.25",
            "vendor": "Metro Line",
            "category": "Transport",
        },
    }
    descriptors = [replay.descriptor_for(image) for image in images]
    return {
        "kind": replay.REPLAY_KIND,
        "schema_version": 1,
        "batch": {
            "digest": replay.batch_digest(descriptors),
            "items": [
                {
                    "input": descriptor.model_dump(mode="json"),
                    "output": outputs[descriptor.name],
                }
                for descriptor in descriptors
            ],
        },
    }


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(
        payload,
        allow_nan=False,
        ensure_ascii=True,
        indent=2,
        sort_keys=True,
    )
    path.write_text(
        f"{serialized}\n",
        encoding="ascii",
    )


def _run(
    repository: Path,
    arguments: Sequence[str],
) -> str:
    environment = os.environ.copy()
    environment.pop("OPENAI_API_KEY", None)
    environment.pop("PYTEST_ADDOPTS", None)
    environment["COLUMNS"] = "96"
    environment["LINES"] = "30"
    environment["LC_ALL"] = "C.UTF-8"
    environment["PYTHONPATH"] = os.pathsep.join(
        [
            str(repository / "src"),
            environment.get("PYTHONPATH", ""),
        ]
    ).rstrip(os.pathsep)
    completed = subprocess.run(
        [sys.executable, "-m", "receipt_extractor.main", *arguments],
        cwd=repository,
        env=environment,
        check=False,
        capture_output=True,
        text=True,
        timeout=15,
    )
    if completed.returncode != 0 or completed.stderr:
        raise RuntimeError(
            f"demo command failed with status {completed.returncode}; "
            "stderr intentionally suppressed"
        )
    return completed.stdout


def _wrapped_lines(text: str, *, width: int = 112) -> list[str]:
    lines: list[str] = []
    for raw_line in text.rstrip().splitlines():
        if not raw_line:
            lines.append("")
            continue
        lines.extend(
            textwrap.wrap(
                raw_line,
                width=width,
                subsequent_indent="  ",
                replace_whitespace=False,
                drop_whitespace=False,
                break_long_words=True,
                break_on_hyphens=False,
            )
        )
    return lines


def _terminal_capture(
    *,
    title: str,
    command: str,
    output: str,
) -> Image.Image:
    command_lines = _wrapped_lines(f"$ {command}")
    output_lines = _wrapped_lines(output)
    line_height = 28
    height = max(
        430,
        112 + (len(command_lines) + len(output_lines) + 2) * line_height,
    )
    image = Image.new("RGB", (1440, height), CANVAS)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle(
        (24, 24, 1416, height - 24),
        radius=24,
        fill=PANEL,
        outline="#293653",
        width=2,
    )
    for x, color in ((58, RED), (84, AMBER), (110, GREEN)):
        draw.ellipse((x - 8, 50, x + 8, 66), fill=color)
    draw.text((136, 43), title, font=_font(22), fill=TEXT)
    draw.line((42, 86, 1398, 86), fill="#293653", width=2)

    y = 108
    for line in command_lines:
        draw.text((58, y), line, font=_font(20), fill=GREEN)
        y += line_height
    y += 12
    for line in output_lines:
        color = CYAN if line.lstrip().startswith(("{", "}", "[", "]")) else TEXT
        draw.text((58, y), line, font=_font(20), fill=color)
        y += line_height
    return image


def _receipt_montage(input_dir: Path) -> Image.Image:
    image = Image.new("RGB", (1440, 900), CANVAS)
    draw = ImageDraw.Draw(image)
    draw.text((72, 54), "Deterministic synthetic inputs", font=_font(42), fill=TEXT)
    draw.text(
        (74, 112),
        "Real PNG + lossless WebP decoded by the production preflight",
        font=_font(23),
        fill=MUTED,
    )
    paths = (input_dir / "cafe-lumen.png", input_dir / "metro-line.webp")
    captions = ("cafe-lumen.png", "metro-line.webp")
    for index, (path, caption) in enumerate(zip(paths, captions, strict=True)):
        with Image.open(path) as receipt:
            rendered = ImageOps.contain(receipt.convert("RGB"), (460, 690))
        x = 196 + index * 660
        y = 170
        draw.rounded_rectangle(
            (x - 20, y - 20, x + 480, y + 710),
            radius=26,
            fill=PANEL,
            outline="#293653",
            width=2,
        )
        image.paste(rendered, (x + (460 - rendered.width) // 2, y))
        caption_width = _text_width(draw, caption, size=23)
        draw.text(
            (x + (460 - caption_width) // 2, 810),
            caption,
            font=_font(23),
            fill=CYAN,
        )
    return image


def _collect_test_count(repository: Path) -> int:
    environment = os.environ.copy()
    environment.pop("PYTEST_ADDOPTS", None)
    environment["PYTHONPATH"] = str(repository / "src")
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=repository,
        env=environment,
        check=True,
        capture_output=True,
        text=True,
        timeout=30,
    )
    matched = re.search(r"(\d+) tests? collected", completed.stdout)
    if matched is None:
        raise RuntimeError("could not derive the collected test count")
    return int(matched.group(1))


def _coverage_summary(coverage_path: Path, *, test_count: int) -> dict[str, Any]:
    decoded = json.loads(coverage_path.read_text(encoding="utf-8"))
    selected = (
        ("file_io", "src/receipt_extractor/file_io.py"),
        ("main", "src/receipt_extractor/main.py"),
        ("replay", "src/receipt_extractor/replay.py"),
        ("gpt", "src/receipt_extractor/gpt.py"),
        ("schema", "src/receipt_extractor/schema.py"),
    )
    files = decoded["files"]
    modules = [
        {
            "module": label,
            "percent": round(float(files[path]["summary"]["percent_covered"]), 2),
        }
        for label, path in selected
    ]
    return {
        "schema_version": 1,
        "command": "make check",
        "test_count": test_count,
        "combined_percent": round(
            float(decoded["totals"]["percent_covered"]),
            2,
        ),
        "modules": modules,
    }


def _coverage_png(summary: dict[str, Any]) -> Image.Image:
    width, height = 1440, 820
    image = Image.new("RGB", (width, height), CANVAS)
    draw = ImageDraw.Draw(image)
    draw.text((72, 54), "Offline verification coverage", font=_font(42), fill=TEXT)
    draw.text(
        (74, 112),
        (
            f"{summary['test_count']} tests  |  "
            f"{summary['combined_percent']:.2f}% combined line/branch coverage"
        ),
        font=_font(23),
        fill=MUTED,
    )
    modules = summary["modules"]
    for index, module in enumerate(modules):
        y = 202 + index * 108
        label = str(module["module"])
        percent = float(module["percent"])
        draw.text((78, y + 14), label, font=_font(25), fill=TEXT)
        draw.rounded_rectangle(
            (260, y, 1280, y + 58),
            radius=18,
            fill=PANEL_LIGHT,
        )
        fill_width = int(1020 * percent / 100)
        color = GREEN if percent >= 90 else AMBER
        draw.rounded_rectangle(
            (260, y, 260 + fill_width, y + 58),
            radius=18,
            fill=color,
        )
        draw.text(
            (1300, y + 14),
            f"{percent:.2f}%",
            font=_font(22),
            fill=color,
        )
    draw.text(
        (78, 758),
        "Generated from coverage.py JSON after the full synthetic/offline suite.",
        font=_font(20),
        fill=MUTED,
    )
    return image


def _svg_text(
    *,
    x: int,
    y: int,
    text: str,
    size: int,
    color: str = TEXT,
    anchor: str = "middle",
    weight: int = 600,
) -> str:
    escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return (
        f'<text x="{x}" y="{y}" text-anchor="{anchor}" '
        f'font-family="system-ui, sans-serif" font-size="{size}" '
        f'font-weight="{weight}" fill="{color}">{escaped}</text>'
    )


def _architecture_svg() -> str:
    nodes = (
        (55, 300, 210, 118, "Receipt batch", "PNG / JPEG / WebP", CYAN),
        (330, 300, 240, 118, "Pinned preflight", "file_io.py", GREEN),
        (665, 96, 230, 108, "Dry-run", "audit metadata", PURPLE),
        (665, 300, 230, 118, "Exact replay", "replay.py", AMBER),
        (665, 530, 230, 118, "Live Responses", "gpt.py", RED),
        (985, 300, 220, 118, "Typed boundary", "ReceiptFields", GREEN),
        (1260, 300, 150, 118, "Private sink", "0600 / stdout", CYAN),
        (330, 600, 240, 108, "Replay manifest", "strict JSON + digest", AMBER),
    )
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="800" '
        'viewBox="0 0 1440 800" role="img" '
        'aria-labelledby="title description">',
        '<title id="title">Auditable Receipt Extractor architecture</title>',
        (
            '<desc id="description">The real CLI flow from bounded receipt inputs '
            "through preflight, dry-run, exact replay or live Responses, typed "
            "validation, and an explicit private sink.</desc>"
        ),
        f'<rect width="1440" height="800" fill="{CANVAS}"/>',
        "<defs>",
        (
            f'<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" '
            'markerWidth="8" markerHeight="8" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{MUTED}"/></marker>'
        ),
        "</defs>",
        _svg_text(
            x=52,
            y=66,
            text="One preflight, three explicit execution modes",
            size=34,
            anchor="start",
        ),
        _svg_text(
            x=54,
            y=105,
            text=(
                "Replay and live share one typed boundary; dry-run emits "
                "audit metadata."
            ),
            size=20,
            color=MUTED,
            anchor="start",
            weight=400,
        ),
    ]
    arrows = (
        "M 265 359 L 330 359",
        "M 570 350 L 665 150",
        "M 570 359 L 665 359",
        "M 570 368 L 665 584",
        "M 570 654 L 665 398",
        "M 895 150 C 1050 150 1120 240 1260 330",
        "M 895 359 L 985 359",
        "M 895 584 C 940 584 940 398 985 398",
        "M 1205 359 L 1260 359",
    )
    parts.extend(
        f'<path d="{path}" stroke="{MUTED}" '
        'stroke-width="3" fill="none" marker-end="url(#arrow)"/>'
        for path in arrows
    )
    for x, y, width, height, title, subtitle, accent in nodes:
        parts.extend(
            (
                (
                    f'<rect x="{x}" y="{y}" width="{width}" height="{height}" '
                    f'rx="22" fill="{PANEL}" stroke="{accent}" stroke-width="3"/>'
                ),
                _svg_text(
                    x=x + width // 2,
                    y=y + 50,
                    text=title,
                    size=22,
                ),
                _svg_text(
                    x=x + width // 2,
                    y=y + 82,
                    text=subtitle,
                    size=16,
                    color=MUTED,
                    weight=400,
                ),
            )
        )
    parts.extend(
        (
            _svg_text(
                x=780,
                y=742,
                text="Offline: no key, no OpenAI import",
                size=18,
                color=AMBER,
            ),
            _svg_text(
                x=780,
                y=772,
                text="Live: explicit upload acknowledgement + explicit sink",
                size=18,
                color=RED,
            ),
            "</svg>",
        )
    )
    return "".join(parts)


def _coverage_svg(summary: dict[str, Any]) -> str:
    width, height = 1080, 620
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
        f'height="{height}" viewBox="0 0 {width} {height}" role="img" '
        'aria-labelledby="title description">',
        '<title id="title">Offline verification coverage</title>',
        (
            f'<desc id="description">{summary["test_count"]} tests with '
            f"{summary['combined_percent']:.2f}% combined line and branch "
            "coverage.</desc>"
        ),
        f'<rect width="{width}" height="{height}" rx="24" fill="{CANVAS}"/>',
        _svg_text(
            x=50,
            y=58,
            text="Offline verification coverage",
            size=32,
            anchor="start",
        ),
        _svg_text(
            x=52,
            y=94,
            text=(
                f"{summary['test_count']} tests  |  "
                f"{summary['combined_percent']:.2f}% combined line/branch"
            ),
            size=18,
            color=MUTED,
            anchor="start",
            weight=400,
        ),
    ]
    for index, module in enumerate(summary["modules"]):
        y = 142 + index * 82
        percent = float(module["percent"])
        bar_width = round(710 * percent / 100)
        color = GREEN if percent >= 90 else AMBER
        parts.extend(
            (
                _svg_text(
                    x=52,
                    y=y + 31,
                    text=str(module["module"]),
                    size=20,
                    anchor="start",
                ),
                (
                    f'<rect x="180" y="{y}" width="710" height="42" rx="13" '
                    f'fill="{PANEL_LIGHT}"/>'
                ),
                (
                    f'<rect x="180" y="{y}" width="{bar_width}" height="42" '
                    f'rx="13" fill="{color}"/>'
                ),
                _svg_text(
                    x=1018,
                    y=y + 29,
                    text=f"{percent:.2f}%",
                    size=18,
                    color=color,
                    anchor="end",
                ),
            )
        )
    parts.extend(
        (
            _svg_text(
                x=52,
                y=584,
                text="Source: coverage.py JSON emitted by make check",
                size=16,
                color=MUTED,
                anchor="start",
                weight=400,
            ),
            "</svg>",
        )
    )
    return "".join(parts)


def _gif_frame(source: Image.Image, *, label: str) -> Image.Image:
    frame = Image.new("RGB", (1200, 760), CANVAS)
    contained = ImageOps.contain(source.convert("RGB"), (1120, 650))
    frame.paste(
        contained,
        ((1200 - contained.width) // 2, 70 + (650 - contained.height) // 2),
    )
    draw = ImageDraw.Draw(frame)
    draw.rounded_rectangle((32, 20, 1168, 64), radius=16, fill=PANEL)
    draw.text((56, 31), label, font=_font(21), fill=TEXT)
    return frame


def _save_assets(
    *,
    asset_dir: Path,
    input_dir: Path,
    help_output: str,
    dry_run_output: str,
    replay_output: str,
    coverage: dict[str, Any],
) -> None:
    asset_dir.mkdir(parents=True, exist_ok=True)
    montage = _receipt_montage(input_dir)
    help_capture = _terminal_capture(
        title="Actual source CLI surface",
        command="PYTHONPATH=src python -m receipt_extractor.main --help",
        output=help_output,
    )
    dry_capture = _terminal_capture(
        title="Actual dry-run output",
        command=(
            "PYTHONPATH=src python -m receipt_extractor.main demo/inputs --dry-run"
        ),
        output=dry_run_output,
    )
    replay_capture = _terminal_capture(
        title="Actual exact-batch replay output",
        command=(
            "PYTHONPATH=src python -m receipt_extractor.main demo/inputs "
            "--replay demo/replay-manifest.json --stdout"
        ),
        output=replay_output,
    )
    coverage_image = _coverage_png(coverage)

    raster_assets = {
        "demo-receipts.png": montage,
        "cli-help.png": help_capture,
        "cli-dry-run.png": dry_capture,
        "cli-replay.png": replay_capture,
        "coverage.png": coverage_image,
    }
    for name, image in raster_assets.items():
        image.save(asset_dir / name, format="PNG", compress_level=9)

    (asset_dir / "architecture.svg").write_text(
        _architecture_svg(),
        encoding="utf-8",
    )
    (asset_dir / "coverage.svg").write_text(
        _coverage_svg(coverage),
        encoding="utf-8",
    )
    frames = [
        _gif_frame(montage, label="1 / 5  Generate explicit synthetic receipts"),
        _gif_frame(help_capture, label="2 / 5  Inspect the real CLI contract"),
        _gif_frame(dry_capture, label="3 / 5  Preflight every input locally"),
        _gif_frame(replay_capture, label="4 / 5  Reproduce the exact batch offline"),
        _gif_frame(coverage_image, label="5 / 5  Verify the complete offline gate"),
    ]
    frames[0].save(
        asset_dir / "demo.gif",
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        duration=(2200, 2200, 2700, 3000, 2600),
        loop=0,
        disposal=2,
        optimize=False,
    )


def capture(
    *,
    repository: Path,
    output_root: Path,
    coverage_path: Path,
) -> None:
    demo_dir = output_root / "demo"
    input_dir = demo_dir / "inputs"
    evidence_dir = demo_dir / "evidence"
    asset_dir = output_root / "docs" / "assets"
    _save_inputs(input_dir)
    images = file_io.load_images(input_dir)
    manifest_path = demo_dir / "replay-manifest.json"
    _write_json(manifest_path, _manifest_document(images))

    help_output = _run(repository, ["--help"])
    dry_run_output = _run(repository, [str(input_dir), "--dry-run"])
    replay_output = _run(
        repository,
        [
            str(input_dir),
            "--replay",
            str(manifest_path),
            "--stdout",
        ],
    )
    evidence_dir.mkdir(parents=True, exist_ok=True)
    (evidence_dir / "help.txt").write_text(help_output, encoding="utf-8")
    (evidence_dir / "dry-run.json").write_text(dry_run_output, encoding="ascii")
    (evidence_dir / "replay-result.json").write_text(
        replay_output,
        encoding="ascii",
    )

    coverage = _coverage_summary(
        coverage_path,
        test_count=_collect_test_count(repository),
    )
    _write_json(evidence_dir / "coverage-summary.json", coverage)
    _save_assets(
        asset_dir=asset_dir,
        input_dir=input_dir,
        help_output=help_output,
        dry_run_output=dry_run_output,
        replay_output=replay_output,
        coverage=coverage,
    )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-root",
        type=Path,
        required=True,
        help="root receiving demo/ and docs/assets/",
    )
    parser.add_argument(
        "--coverage-json",
        type=Path,
        required=True,
        help="coverage.py JSON from the current full test run",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    repository = Path(__file__).resolve().parents[1]
    capture(
        repository=repository,
        output_root=args.output_root.resolve(),
        coverage_path=args.coverage_json.resolve(),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
